------INIT.LUA------
--------------------
require('plugins')
require('keymaps')
require('statusline')
require('treesitter')
require('autopairs')
require('go')
require('tree')
require('completion')
require('settings')
--------------------
